### PR TITLE
add github-actions

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

I add [github-actions](https://docs.github.com/en/actions) and [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) for github-actions. I hope it is useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by andreaspeters** [comment]
@theavege Thanks for your PR. 😀

**Comment by theavege** [comment]
@andreaspeters  Will be it interesting for you to join to the [LXQT](https://lxqt-project.org/about/) project like [lazpaint](https://github.com/bgrabitmap/lazpaint/issues/591)?

**Comment by andreaspeters** [comment]
It depends what I have to do. 😅

**Comment by theavege** [comment]
You may suggest including aprsmap(qt) in LXQT.

**Pull request merged**
